database:
  redis:
    toggle: false
    address: 0.0.0.0
    port: 6379
    user: root
    password: ""
    ssl: false
    prefix: ""
  mongo:
    toggle: false
    connectionURL: "mongodb://root:@localhost:27017/?retryWrites=true&w=majority"
networking:
  ip: 0.0.0.0
  port: 8080
  tcp-fast-open: true
  tcp-no-delay: true
  # AUTO (Find the best case)
  # IO_URING
  # EPOLL
  # KQUEUE
  # NIO
  transport: AUTO
  max-time-out: 10 #s
  write-buffer-watermark:
    low: 1048576 #bytes
    high: 2097152 #bytes
cache:
  message-size: 50
ssl:
  toggleUsingWSS: false
  toggleUsingKeys: false
  certificateFile: ""
  privateKeyFile: ""
rate-limiter:
  authentication:
    delay: 1000 #ms
  send-message:
    max-size: 2000 #character
    time: 5000 #ms
    tokens: 10
  request-bulk-message:
    time: 1000 #ms
    tokens: 5
  can-send-message:
    time: 1000 #ms
    tokens: 5


jwt-secret:
  file: "secret.txt"