database:
  redis:
    toggle: false
    address: 0.0.0.0
    port: 6379
    user: root
    password: ""
    ssl: false
    prefix: ""
  mongo:
    toggle: false
    connectionURL: "mongodb://root:@localhost:27017/?retryWrites=true&w=majority"
  elastic:
    toggle: false
    address: ""
    port: 9200
    user: ""
    password: ""
networking:
  ip: 0.0.0.0
  port: 25565
  tcp-fast-open: true
  tcp-no-delay: true
  # AUTO (Find the best case)
  # IO_URING
  # EPOLL
  # KQUEUE
  # NIO
  transport: AUTO
  max-time-out: 10 #s
  write-buffer-watermark:
    low: 1048576
    high: 2097152
cache:
  message-size: 50
ssl:
  toggleUsingWSS: false
  toggleUsingKeys: false
  certificateFile: ""
  privateKeyFile: ""
rate-limiter:
  send-message:
    max-size: 2000 #character
    time: 5
    tokens: 10