database:
  redis:
    toggle: false
    address: ""
    port: ""
    user: ""
    password: ""
    ssl: true
    prefix: ""
  mongodb:
    toggle: false
    mongoUrl: ""
  elastic:
    toggle: false
    address: ""
    port: ""
    user: ""
    password: ""
networking:
  ip: 0.0.0.0
  port: 25565
  tcp-fast-open: true
  tcp-no-delay: true
  # AUTO (Find the best case)
  # IO_URING
  # EPOLL
  # KQUEUE
  # NIO
  transport: auto
  #max uses all the runtime processors
  threads: max
  write-buffer-watermark:
    low: 1048576
    high: 2097152
cache:
  message-cache-size: 10