name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Dump workspace to debug
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of repo:"
          ls -R .
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: teixayo/bytetalk:latest

      - name: Trigger production server to pull new image
        run: |
          curl -X POST ${{ secrets.PRODUCTION_WEBHOOK_URL }} -H "Authorization: Bearer ${{ secrets.DOCKER_PASSWORD }}"
