name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & push image from frontend
        run: |
          cd frontend
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t teixayo/bytetalk-frontend:latest .
          docker push teixayo/bytetalk-frontend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Trigger production webhook
        run: |
          curl -X POST ${{ secrets.PRODUCTION_BACKEND_WEBHOOK_URL }} -H "Authorization: Bearer ${{ secrets.BACKEND_WEBHOOK_SECRET }}"
