name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build & push image from frontend
        run: |
          cd frontend
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build \
            --build-arg SERVER_WEBSOCKET_URL=${{ secrets.SERVER_WEBSOCKET_URL }} \
            -t teixayo/bytetalk-frontend:latest .
          docker push teixayo/bytetalk-frontend:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}